from sqlalchemy import DateTime, Float, Integer, Column, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class FarmersMarket(Base):
    __tablename__ = 'farmers_markets'

    listing_id = Column(Integer, primary_key=True)
    update_time = Column(DateTime)
    listing_name = Column(String)
    location_address = Column(String)
    orgnization = Column(String)
    orgnization_1 = Column(Integer)
    orgnization_2 = Column(Integer)
    orgnization_3 = Column(Integer)
    orgnization_4 = Column(Integer)
    orgnization_888 = Column(Integer)
    orgnization_1_desc = Column(String)
    orgnization_2_desc = Column(String)
    orgnization_3_desc = Column(String)
    orgnization_4_desc = Column(String)
    orgnization_other_desc = Column(String)
    diversegroup = Column(String)
    diversegroup_1 = Column(Integer)
    diversegroup_2 = Column(Integer)
    diversegroup_3 = Column(Integer)
    diversegroup_4 = Column(Integer)
    diversegroup_5 = Column(Integer)
    diversegroup_6 = Column(Integer)
    diversegroup_888 = Column(Integer)
    diversegroup_other_desc = Column(String)
    listing_desc = Column(String)
    location_x = Column(Float)
    location_y = Column(Float)
    location_desc = Column(String)
    location_site = Column(String)
    location_site_otherdesc = Column(String)
    location_indoor = Column(String)
    specialproductionmethods = Column(String)
    specialproductionmethods_1 = Column(Integer)
    specialproductionmethods_2 = Column(Integer)
    specialproductionmethods_3 = Column(Integer)
    specialproductionmethods_4 = Column(Integer)
    specialproductionmethods_5 = Column(Integer)
    specialproductionmethods_6 = Column(Integer)
    specialproductionmethods_7 = Column(Integer)
    specialproductionmethods_8 = Column(Integer)
    specialproductionmethods_9 = Column(Integer)
    specialproductionmethods_10 = Column(Integer)
    specialproductionmethods_11 = Column(Integer)
    specialproductionmethods_12 = Column(Integer)
    specialproductionmethods_13 = Column(Integer)
    specialproductionmethods_14 = Column(Integer)
    specialproductionmethods_888 = Column(Integer)
    specialproductionmethods_other_desc = Column(String)
    saleschannel_onlineorder = Column(String)
    saleschannel_onlineorder_1 = Column(Integer)
    saleschannel_onlineorder_2 = Column(Integer)
    saleschannel_onlineorder_3 = Column(Integer)
    saleschannel_onlineorder_2_desc = Column(String)
    saleschannel_onlineorder_3_desc = Column(String)
    saleschannel_onlineorder_other_desc = Column(String)
    saleschannel_phoneorder = Column(String)
    saleschannel_csaorder = Column(String)
    saleschannel_csaorder_1 = Column(Integer)
    saleschannel_csaorder_2 = Column(Integer)
    saleschannel_csaorder_3 = Column(Integer)
    saleschannel_csaorder_1_desc = Column(String)
    saleschannel_csaorder_2_desc = Column(String)
    saleschannel_csaorder_3_desc = Column(String)
    saleschannel_csa_vendor = Column(String)
    saleschannel_csa_vendor_1 = Column(Integer)
    saleschannel_csa_vendor_2 = Column(Integer)
    saleschannel_deliverymethod = Column(String)
    saleschannel_deliverymethod_1 = Column(Integer)
    saleschannel_deliverymethod_2 = Column(Integer)
    saleschannel_deliverymethod_3 = Column(Integer)
    saleschannel_deliverymethod_2_desc = Column(String)
    acceptedpayment = Column(String)
    acceptedpayment_1 = Column(Integer)
    acceptedpayment_2 = Column(Integer)
    acceptedpayment_3 = Column(Integer)
    acceptedpayment_4 = Column(Integer)
    acceptedpayment_5 = Column(Integer)
    acceptedpayment_6 = Column(Integer)
    acceptedpayment_7 = Column(Integer)
    acceptedpayment_888 = Column(Integer)
    acceptedpayment_7_desc = Column(String)
    acceptedpayment_other_desc = Column(String)
    FNAP = Column(String)
    FNAP_1 = Column(Integer)
    FNAP_2 = Column(Integer)
    FNAP_3 = Column(Integer)
    FNAP_4 = Column(Integer)
    FNAP_5 = Column(Integer)
    FNAP_888 = Column(Integer)
    SNAP_option = Column(String)
    SNAP_option_1 = Column(Integer)
    SNAP_option_2 = Column(Integer)
    FNAP_3_desc = Column(String)
    webscriping = Column(Integer)
    _location_x = Column('location_x', String)
    _location_y = Column('location_y', String)


    @property
    def location_x(self):
        return self._clean_and_convert_to_float(self._location_x)

    @property
    def location_y(self):
        return self._clean_and_convert_to_float(self._location_y)

    def _clean_and_convert_to_float(self, value):
        if isinstance(value, str):
            if value is not None:
                return float(value.replace(',', ''))
            else:
                return None
        else:
            return value
